name: Salsita Cypress tests
on:
  push:
    branches: 
      - 'master'
  pull_request:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.17.1-chrome106-ff105-edge
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

